{ Parsed from AVFoundation.framework (MacOSX10.10) AVAnimation.h }
{ Created on Sun Mar 8 1:47:27 2015 }

{$ifdef EXTERNAL_SYMBOLS}
var
  AVCoreAnimationBeginTimeAtZero: CFTimeInterval { available in 10_7, 4_0 }; cvar; external;
  AVLayerVideoGravityResizeAspect: NSString { available in 10_7, 4_0 }; cvar; external;
  AVLayerVideoGravityResizeAspectFill: NSString { available in 10_7, 4_0 }; cvar; external;
  AVLayerVideoGravityResize: NSString { available in 10_7, 4_0 }; cvar; external;
{$endif}

