{ Parsed from AVFoundation.framework (MacOSX10.10) AVAudioProcessingSettings.h }
{ Created on Sun Mar 8 1:47:27 2015 }

{$ifdef EXTERNAL_SYMBOLS}
var
  AVAudioTimePitchAlgorithmLowQualityZeroLatency: NSString { available in 7_0 }; cvar; external;
  AVAudioTimePitchAlgorithmTimeDomain: NSString { available in 10_9, 7_0 }; cvar; external;
  AVAudioTimePitchAlgorithmSpectral: NSString { available in 10_9, 7_0 }; cvar; external;
  AVAudioTimePitchAlgorithmVarispeed: NSString { available in 10_9, 7_0 }; cvar; external;
{$endif}

