{ Parsed from CoreMediaIO.framework (MacOSX10.10) CMIOHardware.h }
{ Created on Sun Mar 8 1:47:37 2015 }

{$if  not (defined(__CMIOHardware_h__))}

{$ifdef TYPES}
const
  kCMIOHardwareNoError = 0;
  kCMIOHardwareNotStoppedError = 'run ';
  kCMIOHardwareNotRunningError = 'stop';
  kCMIOHardwareUnspecifiedError = 'what';
  kCMIOHardwareUnknownPropertyError = 'who?';
  kCMIOHardwareBadPropertySizeError = '!siz';
  kCMIOHardwareIllegalOperationError = 'nope';
  kCMIOHardwareBadObjectError = '!obj';
  kCMIOHardwareBadDeviceError = '!dev';
  kCMIOHardwareBadStreamError = '!str';
  kCMIOHardwareUnsupportedOperationError = 'unop';
  kCMIOHardwareSuspendedBySystemError = 'deny';
  kCMIODeviceUnsupportedFormatError = '!dat';
  kCMIODevicePermissionsError = '!hog';
const
  kCMIOPlugInClassID = 'aplg';
const
  kCMIOPlugInPropertyBundleID = 'piid';
{$endif}

{$endif}
