{ Parsed from AppKit.framework (MacOSX10.10) AppKitErrors.h }
{ Created on Sun Mar 8 1:49:07 2015 }

{$ifdef TYPES}
const
  NSTextReadInapplicableDocumentTypeError = 65806;
  NSTextWriteInapplicableDocumentTypeError = 66062;
  NSTextReadWriteErrorMinimum = 65792;
  NSTextReadWriteErrorMaximum = 66303;
  NSServiceApplicationNotFoundError = 66560;
  NSServiceApplicationLaunchFailedError = 66561;
  NSServiceRequestTimedOutError = 66562;
  NSServiceInvalidPasteboardDataError = 66563;
  NSServiceMalformedServiceDictionaryError = 66564;
  NSServiceMiscellaneousError = 66800;
  NSServiceErrorMinimum = 66560;
  NSServiceErrorMaximum = 66817;
  NSSharingServiceNotConfiguredError = 67072;
  NSSharingServiceErrorMinimum = 67072;
  NSSharingServiceErrorMaximum = 67327;
{$endif}

