{ Parsed from Foundation.framework (MacOSX10.10) NSExtensionItem.h }
{ Created on Sun Mar 8 1:49:14 2015 }

{$ifdef EXTERNAL_SYMBOLS}
var
  NSExtensionItemAttributedTitleKey: NSString { available in 10_10, 8_0 }; cvar; external;
  NSExtensionItemAttributedContentTextKey: NSString { available in 10_10, 8_0 }; cvar; external;
  NSExtensionItemAttachmentsKey: NSString { available in 10_10, 8_0 }; cvar; external;
{$endif}
