{ Parsed from CalendarStore.framework (MacOSX10.10) CalendarStoreErrors.h }
{ Created on Sun Mar 8 1:47:31 2015 }

{$ifdef EXTERNAL_SYMBOLS}
var
  CalCalendarStoreErrorDomain: NSString deprecated 'in 10_5, 10_8'; cvar; external;
{$endif}

{$ifdef TYPES}
const
  CalCalendarNotEditableError = 1025;
  CalDateInvalidError = 1026;
  CalCalendarNotInRepository = 1027;
  CalCalendarTitleNotUniqueError = 1028;
{$endif}

