{ Parsed from CoreBluetooth.framework (MacOSX10.10) CBCentralManagerConstants.h }
{ Created on Sun Mar 8 1:48:05 2015 }

{$ifdef EXTERNAL_SYMBOLS}
var
  CBCentralManagerOptionShowPowerAlertKey: NSString { available in 10_9, 7_0 }; cvar; external;
  CBCentralManagerOptionRestoreIdentifierKey: NSString { available in NA, 7_0 }; cvar; external;
  CBCentralManagerScanOptionAllowDuplicatesKey: NSString; cvar; external;
  CBCentralManagerScanOptionSolicitedServiceUUIDsKey: NSString { available in 10_9, 7_0 }; cvar; external;
  CBConnectPeripheralOptionNotifyOnConnectionKey: NSString { available in NA, 6_0 }; cvar; external;
  CBConnectPeripheralOptionNotifyOnDisconnectionKey: NSString; cvar; external;
  CBConnectPeripheralOptionNotifyOnNotificationKey: NSString { available in NA, 6_0 }; cvar; external;
  CBCentralManagerRestoredStatePeripheralsKey: NSString { available in NA, 7_0 }; cvar; external;
  CBCentralManagerRestoredStateScanServicesKey: NSString { available in NA, 7_0 }; cvar; external;
  CBCentralManagerRestoredStateScanOptionsKey: NSString { available in NA, 7_0 }; cvar; external;
{$endif}

