{ Parsed from CoreBluetooth.framework (MacOSX10.10) CBPeripheralManagerConstants.h }
{ Created on Sun Mar 8 1:48:05 2015 }

{$ifdef EXTERNAL_SYMBOLS}
var
  CBPeripheralManagerOptionShowPowerAlertKey: NSString { available in 10_9, 7_0 }; cvar; external;
  CBPeripheralManagerOptionRestoreIdentifierKey: NSString { available in NA, 7_0 }; cvar; external;
  CBPeripheralManagerRestoredStateServicesKey: NSString { available in NA, 7_0 }; cvar; external;
  CBPeripheralManagerRestoredStateAdvertisementDataKey: NSString { available in NA, 7_0 }; cvar; external;
{$endif}

