{ Parsed from ServiceManagement.framework (MacOSX10.10) SMErrors.h }
{ Created on Sun Mar 8 1:48:22 2015 }

{$ifndef __SERVICE_MANAGEMENT_ERRORS__}
{$ifdef TYPES}
const
  kSMErrorInternalFailure = 2;
  kSMErrorInvalidSignature = 3;
  kSMErrorAuthorizationFailure = 4;
  kSMErrorToolNotValid = 5;
  kSMErrorJobNotFound = 6;
  kSMErrorServiceUnavailable = 7;
  kSMErrorJobPlistNotFound = 8;
  kSMErrorJobMustBeEnabled = 9;
  kSMErrorInvalidPlist = 10;
{$endif}

{$endif}
