{ Parsed from DiscRecording.framework DRContentProperties.h }

{$ifndef _H_DRContentProperties}

{$ifdef EXTERNAL_SYMBOLS}
var
  kDRISOLevel: CFStringRef; cvar; external;
  kDRVolumeSet: CFStringRef; cvar; external;
  kDRPublisher: CFStringRef; cvar; external;
  kDRDataPreparer: CFStringRef; cvar; external;
  kDRSystemIdentifier: CFStringRef; cvar; external;
  kDRApplicationIdentifier: CFStringRef; cvar; external;
  kDRCopyrightFile: CFStringRef; cvar; external;
  kDRAbstractFile: CFStringRef; cvar; external;
  kDRBibliographicFile: CFStringRef; cvar; external;
  kDRBlockSize: CFStringRef; cvar; external;
  kDRDefaultDate: CFStringRef; cvar; external;
  kDRVolumeCreationDate: CFStringRef; cvar; external;
  kDRVolumeModificationDate: CFStringRef; cvar; external;
  kDRVolumeCheckedDate: CFStringRef; cvar; external;
  kDRVolumeExpirationDate: CFStringRef; cvar; external;
  kDRVolumeEffectiveDate: CFStringRef; cvar; external;
  kDRISOMacExtensions: CFStringRef; cvar; external;
  kDRISORockRidgeExtensions: CFStringRef; cvar; external;
  kDRSuppressMacSpecificFiles: CFStringRef; cvar; external;
  kDRAllFilesystems: CFStringRef; cvar; external;
  kDRISO9660: CFStringRef; cvar; external;
  kDRISO9660LevelOne: CFStringRef; cvar; external;
  kDRISO9660LevelTwo: CFStringRef; cvar; external;
  kDRJoliet: CFStringRef; cvar; external;
  kDRHFSPlus: CFStringRef; cvar; external;
  kDRUDF: CFStringRef; cvar; external;
  kDRISO9660VersionNumber: CFStringRef; cvar; external;
  kDRInvisible: CFStringRef; cvar; external;
  kDRCreationDate: CFStringRef; cvar; external;
  kDRContentModificationDate: CFStringRef; cvar; external;
  kDRAttributeModificationDate: CFStringRef; cvar; external;
  kDRAccessDate: CFStringRef; cvar; external;
  kDRBackupDate: CFStringRef; cvar; external;
  kDRRecordingDate: CFStringRef; cvar; external;
  kDREffectiveDate: CFStringRef; cvar; external;
  kDRExpirationDate: CFStringRef; cvar; external;
  kDRPosixFileMode: CFStringRef; cvar; external;
  kDRPosixUID: CFStringRef; cvar; external;
  kDRPosixGID: CFStringRef; cvar; external;
  kDRHFSPlusTextEncodingHint: CFStringRef; cvar; external;
  kDRHFSPlusCatalogNodeID: CFStringRef; cvar; external;
  kDRMacFileType: CFStringRef; cvar; external;
  kDRMacFileCreator: CFStringRef; cvar; external;
  kDRMacWindowBounds: CFStringRef; cvar; external;
  kDRMacIconLocation: CFStringRef; cvar; external;
  kDRMacScrollPosition: CFStringRef; cvar; external;
  kDRMacWindowView: CFStringRef; cvar; external;
  kDRMacFinderFlags: CFStringRef; cvar; external;
  kDRMacExtendedFinderFlags: CFStringRef; cvar; external;
  kDRMacFinderHideExtension: CFStringRef; cvar; external;
  kDRUDFWriteVersion: CFStringRef; cvar; external;
  kDRUDFVersion102: CFStringRef; cvar; external;
  kDRUDFVersion150: CFStringRef; cvar; external;
  kDRUDFPrimaryVolumeDescriptorNumber: CFStringRef; cvar; external;
  kDRUDFVolumeSequenceNumber: CFStringRef; cvar; external;
  kDRUDFMaxVolumeSequenceNumber: CFStringRef; cvar; external;
  kDRUDFInterchangeLevel: CFStringRef; cvar; external;
  kDRUDFMaxInterchangeLevel: CFStringRef; cvar; external;
  kDRUDFApplicationIdentifierSuffix: CFStringRef; cvar; external;
  kDRUDFVolumeSetIdentifier: CFStringRef; cvar; external;
  kDRUDFVolumeSetTimestamp: CFStringRef; cvar; external;
  kDRUDFVolumeSetImplementationUse: CFStringRef; cvar; external;
  kDRUDFRealTimeFile: CFStringRef; cvar; external;
  kDRUDFExtendedFilePermissions: CFStringRef; cvar; external;
{$endif}

{$endif}
