{ Parsed from DiscRecording.framework (MacOSX10.10) DRCoreStatus.h }
{ Created on Sun Mar 8 1:47:42 2015 }

{$ifndef _H_DRCoreStatus}

{$ifdef EXTERNAL_SYMBOLS}
var
  kDRStatusStateKey: CFStringRef; cvar; external;
  kDRStatusPercentCompleteKey: CFStringRef; cvar; external;
  kDRStatusCurrentSpeedKey: CFStringRef; cvar; external;
  kDRStatusCurrentSessionKey: CFStringRef; cvar; external;
  kDRStatusCurrentTrackKey: CFStringRef; cvar; external;
  kDRStatusTotalSessionsKey: CFStringRef; cvar; external;
  kDRStatusTotalTracksKey: CFStringRef; cvar; external;
  kDRStatusEraseTypeKey: CFStringRef; cvar; external;
  kDRStatusStateNone: CFStringRef; cvar; external;
  kDRStatusStatePreparing: CFStringRef; cvar; external;
  kDRStatusStateVerifying: CFStringRef; cvar; external;
  kDRStatusStateDone: CFStringRef; cvar; external;
  kDRStatusStateFailed: CFStringRef; cvar; external;
  kDRStatusStateSessionOpen: CFStringRef; cvar; external;
  kDRStatusStateTrackOpen: CFStringRef; cvar; external;
  kDRStatusStateTrackWrite: CFStringRef; cvar; external;
  kDRStatusStateTrackClose: CFStringRef; cvar; external;
  kDRStatusStateSessionClose: CFStringRef; cvar; external;
  kDRStatusStateFinishing: CFStringRef; cvar; external;
  kDRStatusStateErasing: CFStringRef; cvar; external;
  kDRStatusProgressInfoKey: CFStringRef; cvar; external;
  kDRStatusProgressCurrentKPS: CFStringRef; cvar; external;
  kDRStatusProgressCurrentXFactor: CFStringRef; cvar; external;
{$endif}

{$endif}
