{ Parsed from DiscRecording.framework DRStatus.h }

{$ifdef EXTERNAL_SYMBOLS}
var
  DRStatusStateKey: NSString; cvar; external;
  DRStatusPercentCompleteKey: NSString; cvar; external;
{$endif}

{$ifdef EXTERNAL_SYMBOLS}
var
  DRStatusCurrentSessionKey: NSString; cvar; external;
  DRStatusCurrentTrackKey: NSString; cvar; external;
  DRStatusTotalSessionsKey: NSString; cvar; external;
  DRStatusTotalTracksKey: NSString; cvar; external;
  DRStatusCurrentSpeedKey: NSString; cvar; external;
{$endif}

{$ifdef EXTERNAL_SYMBOLS}
var
  DRStatusEraseTypeKey: NSString; cvar; external;
{$endif}

{$ifdef EXTERNAL_SYMBOLS}
var
  DRStatusStateNone: NSString; cvar; external;
  DRStatusStatePreparing: NSString; cvar; external;
  DRStatusStateVerifying: NSString; cvar; external;
  DRStatusStateDone: NSString; cvar; external;
  DRStatusStateFailed: NSString; cvar; external;
{$endif}

{$ifdef EXTERNAL_SYMBOLS}
var
  DRStatusStateSessionOpen: NSString; cvar; external;
  DRStatusStateTrackOpen: NSString; cvar; external;
  DRStatusStateTrackWrite: NSString; cvar; external;
  DRStatusStateTrackClose: NSString; cvar; external;
  DRStatusStateSessionClose: NSString; cvar; external;
  DRStatusStateFinishing: NSString; cvar; external;
{$endif}

{$ifdef EXTERNAL_SYMBOLS}
var
  DRStatusStateErasing: NSString; cvar; external;
{$endif}

{$ifdef EXTERNAL_SYMBOLS}
var
  DRStatusProgressInfoKey: NSString; cvar; external;
  DRStatusProgressCurrentKPS: NSString; cvar; external;
  DRStatusProgressCurrentXFactor: NSString; cvar; external;
{$endif}

{$ifdef EXTERNAL_SYMBOLS}
var
  DRErrorStatusKey: NSString; cvar; external;
  DRErrorStatusErrorKey: NSString; cvar; external;
  DRErrorStatusErrorStringKey: NSString; cvar; external;
  DRErrorStatusErrorInfoStringKey: NSString; cvar; external;
  DRErrorStatusSenseKey: NSString; cvar; external;
  DRErrorStatusSenseCodeStringKey: NSString; cvar; external;
  DRErrorStatusAdditionalSenseStringKey: NSString; cvar; external;
{$endif}

