{ Parsed from Social.framework (MacOSX10.10) SLServiceTypes.h }
{ Created on Sun Mar 8 1:46:54 2015 }

{$ifdef EXTERNAL_SYMBOLS}
var
  SLServiceTypeTwitter: NSString { available in 10_8, 6_0 }; cvar; external;
  SLServiceTypeFacebook: NSString { available in 10_8, 6_0 }; cvar; external;
  SLServiceTypeSinaWeibo: NSString { available in 10_8, 6_0 }; cvar; external;
  SLServiceTypeTencentWeibo: NSString { available in 10_9, 7_0 }; cvar; external;
  SLServiceTypeLinkedIn: NSString { available in 10_9, NA }; cvar; external;
{$endif}

